[project]
name = "multi_cam_compose_pro_RUFSHOD"
version = "0.0.1"
authors = [
  { name="Wlinds & Rufshod", email="alexander@11a.se" },
]
description = "PLACEHOLDER: multi_cam_compose_pro is used to take images in order to train a model"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[project.urls]
"Homepage" = "https://github.com/wlinds/mccp"
"Bug Tracker" = "https://github.com/wlinds/mccp/issues"